const COMMON = require('./common');

const VALIDHEADERS = {
    [COMMON.CONSTANTS.REQUEST_HEADER_CONTENT_TYPE]: 'application/json',
    [COMMON.CONSTANTS.REQUEST_HEADER_CORRELATION_ID]: 'e9fe9dc0-3f9b-11eb-b378-0242ac130002',
    [COMMON.CONSTANTS.REQUEST_HEADER_CLIENTID]: 'GENESYS-URS',
    [COMMON.CONSTANTS.REQUEST_HEADER_TIMESTAMP]: '2020-07-21T17:32:28Z',
};

const INVALIDHEADERS = {
    [COMMON.CONSTANTS.REQUEST_HEADER_CONTENT_TYPE]: 'application/json',
    [COMMON.CONSTANTS.REQUEST_HEADER_CORRELATION_ID]: 'e9fe9dc0-3f9b-11eb-b378-0242ac130002',
    // [COMMON.CONSTANTS.REQUEST_HEADER_CLIENTID]: 'GENESYS-URS',
    [COMMON.CONSTANTS.REQUEST_HEADER_TIMESTAMP]: '2020-07-21T17:32:28Z',
};


const VALIDBODY = {
    [COMMON.CONSTANTS.REQUEST_BODY_PARTYID]: 'CX100001',
    [COMMON.CONSTANTS.REQUEST_BODY_APPTAG]: 'apptag_51',
    [COMMON.CONSTANTS.REQUEST_BODY_SERVICECALLTYPE]: 'sct_1',
};

const INVALIDBODY = {
    [COMMON.CONSTANTS.REQUEST_BODY_PARTYID]: 'CX100001',
    [COMMON.CONSTANTS.REQUEST_BODY_APPTAG]: 'apptag_51',
    [COMMON.CONSTANTS.REQUEST_BODY_SERVICECALLTYPE]: 'sct_1',
};


exports.VALIDHEADERS = VALIDHEADERS;
exports.INVALIDHEADERS = INVALIDHEADERS;
exports.VALIDBODY = VALIDBODY;
exports.INVALIDBODY = INVALIDBODY;