'use strict';

// Environment items
const DEVELOPMENT_ENVIRONMENT = 'DEVELOPMENT';
const PRODUCTION_ENVIRONMENT = 'PRODUCTION';

exports.DEVELOPMENT_ENVIRONMENT = DEVELOPMENT_ENVIRONMENT;
exports.PRODUCTION_ENVIRONMENT = PRODUCTION_ENVIRONMENT;

//Default Routing Port and EndPoint
const API_PORT = 8080;
const API_PATH = "/RoutingRecommendations";

exports.API_PORT = API_PORT;
exports.API_PATH = API_PATH;

//Default DB Connection SecretKeys
const DATABASE_CLOUD_SQL_INSTANCE_NAME = "127.0.0.1";
const DATABASE_NAME = "call_routing";
const DATABASE_USERNAME = "postgres";
const DATABASE_PASSWORD = "sky@sky!";
const DATABASE_PORT = 5433;

exports.DATABASE_CLOUD_SQL_INSTANCE_NAME = DATABASE_CLOUD_SQL_INSTANCE_NAME;
exports.DATABASE_NAME = DATABASE_NAME;
exports.DATABASE_USERNAME = DATABASE_USERNAME;
exports.DATABASE_PASSWORD = DATABASE_PASSWORD;
exports.DATABASE_PORT = DATABASE_PORT;



//Data Items
const REQUEST_BODY_PARTYID = "partyId";
const REQUEST_BODY_APPTAG = "appTag";
const REQUEST_BODY_SERVICECALLTYPE = "serviceCallType";
const REQUEST_HEADER_CORRELATION_ID = "x-sky-diagnostic-correlationid";
const REQUEST_HEADER_CLIENTID = "x-sky-diagnostics-clientid";
const REQUEST_HEADER_TIMESTAMP = "x-sky-timestamp";

exports.REQUEST_BODY_PARTYID = REQUEST_BODY_PARTYID;
exports.REQUEST_BODY_APPTAG = REQUEST_BODY_APPTAG;
exports.REQUEST_BODY_SERVICECALLTYPE = REQUEST_BODY_SERVICECALLTYPE;
exports.REQUEST_HEADER_CORRELATION_ID = REQUEST_HEADER_CORRELATION_ID;
exports.REQUEST_HEADER_CLIENTID = REQUEST_HEADER_CLIENTID;
exports.REQUEST_HEADER_TIMESTAMP = REQUEST_HEADER_TIMESTAMP;


//HTTP codes
const HTTP_BAD_REQUEST_CODE = 400;
const HTTP_BAD_REQUEST_CUSTOM_CODE = "400";
const MESSAGE_FOR_HEADER_MISSING = "Request cannot be proccesed due to required headers are missing";
const MESSAGE_FOR_REQUEST_BODY_MISSING = "Request cannot be proccesed due to required request body parameters are missing";

exports.HTTP_BAD_REQUEST_CODE = HTTP_BAD_REQUEST_CODE;
exports.HTTP_BAD_REQUEST_CUSTOM_CODE = HTTP_BAD_REQUEST_CUSTOM_CODE;
exports.MESSAGE_FOR_HEADER_MISSING = MESSAGE_FOR_HEADER_MISSING;
exports.MESSAGE_FOR_REQUEST_BODY_MISSING = MESSAGE_FOR_REQUEST_BODY_MISSING;

const HTTP_UNAUTHORIZATION_CODE = 401;
const HTTP_UNAUTHORIZATION_CUSTOM_CODE = "401";
const DESCRIPTION_AUTHORIZATION_HEADER = 'Authorization Header is missing';
const MESSAGE_FOR_UNAUTHORIZATION_HEADER = 'Invalid Authentication Credentials';
const DESCRIPTION_FOR_UNAUTHORIZATION_HEADER = 'Invalid Authentication Credentials';

exports.HTTP_UNAUTHORIZATION_CODE = HTTP_UNAUTHORIZATION_CODE;
exports.HTTP_UNAUTHORIZATION_CUSTOM_CODE = HTTP_UNAUTHORIZATION_CUSTOM_CODE;
exports.DESCRIPTION_AUTHORIZATION_HEADER = DESCRIPTION_AUTHORIZATION_HEADER;
exports.MESSAGE_FOR_UNAUTHORIZATION_HEADER = MESSAGE_FOR_UNAUTHORIZATION_HEADER;
exports.DESCRIPTION_FOR_UNAUTHORIZATION_HEADER = DESCRIPTION_FOR_UNAUTHORIZATION_HEADER;


const HTTP_RESOURCE_NOT_FOUND_CODE = 404;
const HTTP_RESOURCE_NOT_FOUND_CUSTOM_CODE = "404";
const MESSAGE_FOR_BAD_REQUEST = "Request not found";
const DESCRIPTION_FOR_BAD_REQUEST = "Request not found";

exports.HTTP_RESOURCE_NOT_FOUND_CODE = HTTP_RESOURCE_NOT_FOUND_CODE;
exports.HTTP_RESOURCE_NOT_FOUND_CUSTOM_CODE = HTTP_RESOURCE_NOT_FOUND_CUSTOM_CODE;
exports.MESSAGE_FOR_BAD_REQUEST = MESSAGE_FOR_BAD_REQUEST;
exports.DESCRIPTION_FOR_BAD_REQUEST = DESCRIPTION_FOR_BAD_REQUEST;




const HTTP_UNEXPECTED_ERROR_CODE = 500;
const HTTP_UNEXPECTED_ERROR_CUSTOM_CODE = "500";
const MESSAGE_FOR_UNEXPECTED_ERROR = 'There has been an error getting Insight Recommendations';
const DESCRIPTION_FOR_UNEXPECTED_ERROR = 'Your request could not be processed due to an unknown issue. Please try after sometime or contact support team';

exports.HTTP_UNEXPECTED_ERROR_CODE = HTTP_UNEXPECTED_ERROR_CODE;
exports.HTTP_UNEXPECTED_ERROR_CUSTOM_CODE = HTTP_UNEXPECTED_ERROR_CUSTOM_CODE;
exports.MESSAGE_FOR_UNEXPECTED_ERROR = MESSAGE_FOR_UNEXPECTED_ERROR;
exports.DESCRIPTION_FOR_UNEXPECTED_ERROR = DESCRIPTION_FOR_UNEXPECTED_ERROR;





// Response Items
const RESPONSE_TYPE_SUCCESS = 'SUCCESS';
const RESPONSE_TYPE_FAILURE = 'FAILURE';
const RECOMMENDATION_fOUND = "RECOMMENDATION";
const RECOMMENDATION_OPT_OUT = "GDPR-OPT-OUT";
const PARTYID_NOT_FOUND = "PARTYID-NOT-FOUND";
const APP_TAG_NOT_MODELLED = "APP-TAG-NOT-MODELLED";
const SCT_NOT_FOUND = "SCT-NOT-FOUND";


exports.RESPONSE_TYPE_SUCCESS = RESPONSE_TYPE_SUCCESS;
exports.RESPONSE_TYPE_FAILURE = RESPONSE_TYPE_FAILURE;
exports.RECOMMENDATION_fOUND = RECOMMENDATION_fOUND;
exports.RECOMMENDATION_OPT_OUT = RECOMMENDATION_OPT_OUT;
exports.PARTYID_NOT_FOUND = PARTYID_NOT_FOUND;
exports.APP_TAG_NOT_MODELLED = APP_TAG_NOT_MODELLED;
exports.SCT_NOT_FOUND = SCT_NOT_FOUND;

//Response Keys
// const RESPONSE_RESULT = "result";
// const RESPONSE_RESULT_TYPE = "resultType";
// const RESPONSE_ROUTING_RECOMMENDATION = "routingRecommendation";
// const RESPONSE_MODEL_EXECUTED = "modelExecuted";

// exports.RESPONSE_RESULT = RESPONSE_RESULT;
// exports.RESPONSE_RESULT_TYPE = RESPONSE_RESULT_TYPE;
// exports.RESPONSE_ROUTING_RECOMMENDATION = RESPONSE_ROUTING_RECOMMENDATION;
// exports.RESPONSE_MODEL_EXECUTED = RESPONSE_MODEL_EXECUTED;


